sudo: enabled
dist: xenial
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - gnuradio-dev
      - python-numpy
      - python-pip
install:
  - pip install scikit-commpy
