/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(resource_demapper_cc.h)                                    */
/* BINDTOOL_HEADER_FILE_HASH(5e4a9a5a78c66f8a4170df65bbf15331)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gfdm/resource_demapper_cc.h>
// pydoc.h is automatically generated in the build directory
#include <resource_demapper_cc_pydoc.h>

void bind_resource_demapper_cc(py::module& m)
{

    using resource_demapper_cc = gr::gfdm::resource_demapper_cc;


    py::class_<resource_demapper_cc,
               gr::block,
               gr::basic_block,
               std::shared_ptr<resource_demapper_cc>>(
        m, "resource_demapper_cc", D(resource_demapper_cc))

        .def(py::init(&resource_demapper_cc::make),
             py::arg("timeslots"),
             py::arg("subcarriers"),
             py::arg("active_subcarriers"),
             py::arg("subcarrier_map"),
             py::arg("per_timeslot"),
             D(resource_demapper_cc, make))

        .def("pilots", &resource_demapper_cc::pilots)
        .def("set_pilots", &resource_demapper_cc::set_pilots);
}
